BREEZEWIKI_INSTANCE_URL = "" # YOUR FAVOURITE BREEZEWIKI INSTANCE

MASTODON_URL = "" # YOUR OWN MASTODON PAGE URL
YOUTUBE_URL = "" # YOUR OWN YOUTUBE CHANNEL PAGE URL
VKONTAKTE_URL = "" # YOUR OWN VKONTAKTE (VK) ACCOUNT URL
VKPLAY_URL = "" # YOUR OWN VK PLAY ACCOUNT URL (NEEDED FOR VK PLAY ACTIVITY)
STEAM_URL = "" # YOUR OWN STEAM ACCOUNT URL (NEEDED FOR STEAM ACTIVITY)
TELEGRAM_URL = "" # YOUR OWN TELEGRAM ACCOUNT
MATRIX_URL = "" # MATRIX.TO URL TO YOUR MATRIX ACCOUNT

EMAIL_ADDRESS = "" # YOUR EMAIL

DEBUG = False # FLASK DEBUG MODE

CACHE_TYPE = "SimpleCache" # FLASK-CACHING STORAGE TYPE
CACHE_DEFAULT_TIMEOUT = 300 # CACHE TIMEOUT

STEAM_API_KEY = "" # YOUR OWN STEAM API KEY

FEDIRING_ENABLED = False # FEDIRING IS ENABLED?

SELFHOSTED_ENABLED = False # YOU DO HAVE A PUBLIC SELF HOSTED SERVICES?
SELFHOSTED_NOTE_ABOUT_EU_LOCATION = False # YOUR SERVER IS LOCATED IN NETHERLANDS?

SELFHOSTED_NITTER_URL = "" # YOUR SELF-HOSTED NITTER URL
SELFHOSTED_BREEZEWIKI_URL = "" # YOUR SELF-HOSTED BREEZEWIKI URL
